default['opendkim']['domain'] = "example.com"
default['opendkim']['keyfile'] = "/etc/mail/dkim.key"
default['opendkim']['key_data_bag_name'] = "private"
default['opendkim']['selector'] = "2007"
default['opendkim']['socket'] = "inet:8891@localhost"
default['opendkim']['internal_hosts'] = "127.0.0.1"
default['opendkim']['subdomains'] = "true"
default['opendkim']['trusted_host_role'] = "trusted_host"
